In [2]:
#Using MiniBatch KMeans to handle more data

In [4]:
import numpy as np
from sklearn.datasets import make_blobs
blobs, labels = make_blobs(int(1e6), 3)
 
from sklearn.cluster import KMeans, MiniBatchKMeans
kmeans = KMeans(n_clusters=3)
minibatch = MiniBatchKMeans(n_clusters=3)

In [6]:
%time kmeans.fit(blobs) #IPython Magic

CPU times: user 586 ms, sys: 2.65 s, total: 3.24 s
Wall time: 306 ms


KMeans(n_clusters=3)

In [8]:
%time minibatch.fit(blobs)

CPU times: user 208 ms, sys: 1.51 s, total: 1.71 s
Wall time: 138 ms


MiniBatchKMeans(n_clusters=3)

In [10]:
kmeans.cluster_centers_

array([[ 8.25796971,  8.61494826, -4.30953933],
       [ 9.39595343, -6.30138016,  9.45171302],
       [ 8.03629908,  0.14216359,  1.20870646]])

In [12]:
minibatch.cluster_centers_

array([[ 8.25708179,  8.60658962, -4.31603009],
       [ 9.39365337, -6.31093756,  9.45856873],
       [ 8.0654857 ,  0.13744415,  1.2141222 ]])

In [14]:
from sklearn.metrics import pairwise
pairwise.pairwise_distances(kmeans.cluster_centers_[0].reshape(1, -1), minibatch.cluster_centers_[0].reshape(1, -1))

array([[0.01062004]])

In [16]:
np.diag(pairwise.pairwise_distances(kmeans.cluster_centers_, minibatch.cluster_centers_))

array([0.01062004, 0.01198478, 0.03005765])

In [18]:
minibatch = MiniBatchKMeans(batch_size=len(blobs))
%time minibatch.fit(blobs)

CPU times: user 4.63 s, sys: 9.79 s, total: 14.4 s
Wall time: 1.05 s


MiniBatchKMeans(batch_size=1000000)