In [2]:
#Numpy Basics

In [4]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array_1 = np.arange(10)
array_1.shape

(10,)

In [8]:
array_1.ndim      #Find number of dimensions of array_1

1

In [10]:
array_1.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
array_1 = array_1.reshape((5,2))
array_1.ndim

2

In [14]:
array_1 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
array_2 = np.arange(10)
array_2 * array_2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
array_2 = array_2 ** 2  #Note that this is equivalent to array_2 * array_2
array_2 = array_2.reshape((5,2))
array_2

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [20]:
array_1 = array_1 + 1
array_1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
array_1 + array_2

array([[ 1,  3],
       [ 7, 13],
       [21, 31],
       [43, 57],
       [73, 91]])

In [24]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
import numpy as np

# Create a 5x2 array of ones with integer data type
array = np.ones((5, 2), dtype=int)

print(array)


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [32]:
import numpy as np

# Create a 5x2 uninitialized array with float data type
array = np.empty((5, 2), dtype=float)

print(array)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
array_1[0,0]   #Finds value in first row and first column.

1

In [36]:
array_1[0,:]

array([1, 2])

In [38]:
array_1[:,0]

array([1, 3, 5, 7, 9])

In [40]:
array_1[2:5, :]

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [42]:
array_1[2:5,0]

array([5, 7, 9])

In [44]:
array_1 > 5

array([[False, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [46]:
array_1[array_1 > 5]

array([ 6,  7,  8,  9, 10])

In [48]:
array_1.sum()

55

In [50]:
array_1.sum(axis = 1)

array([ 3,  7, 11, 15, 19])

In [52]:
array_1.sum(axis = 0)

array([25, 30])

In [54]:
array_1.mean(axis = 0)

array([5., 6.])

In [56]:
array_3 = np.array([np.nan, 0, 1, 2, np.nan])
np.isnan(array_3)

array([ True, False, False, False,  True])

In [58]:
array_3[~np.isnan(array_3)]

array([0., 1., 2.])

In [60]:
array_3[np.isnan(array_3)] = 0
array_3

array([0., 0., 1., 2., 0.])