In [2]:
#Creating binary features through thresholding

In [6]:
import numpy as np
from sklearn.datasets import fetch_california_housing

# Load the California housing dataset
california = fetch_california_housing()

# Extract the features (X) and target (y)
X, y = california.data, california.target.reshape(-1, 1)

# Print shapes to verify
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)


Shape of X: (20640, 8)
Shape of y: (20640, 1)


In [16]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn import preprocessing

# Load the California housing dataset
california = fetch_california_housing()

# Extract the features (X) and target (y)
X, y = california.data, california.target.reshape(-1, 1)

# Compute the mean of the target values
threshold = california.target.mean()

# Binarize the target values using the computed mean as the threshold
new_target = preprocessing.binarize(y, threshold=threshold)

# Display the first 5 binarized target values
print(new_target[:5])



[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [18]:
(y[:5] > y.mean()).astype(int)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [24]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn import preprocessing

# Load the California housing dataset
california = fetch_california_housing()

# Extract the features (X) and target (y)
X, y = california.data, california.target.reshape(-1, 1)

# Compute the mean of the target values
threshold = y.mean()

# Binarize the target values using the computed mean as the threshold
binar = preprocessing.Binarizer(threshold=threshold)
new_target = binar.fit_transform(y)

# Display the first 5 binarized target values
print(new_target[:5])


[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [28]:
import numpy as np
from scipy.sparse import coo_matrix
from sklearn.preprocessing import Binarizer

# Create a random sparse matrix using binomial distribution
spar = coo_matrix(np.random.binomial(1, .25, 100).reshape(10, 10))

# Convert the sparse matrix to a dense array for binarization
dense_array = spar.toarray()

# Binarize the dense array using a threshold of -1
binarizer = Binarizer(threshold=-1)
binarized_dense_array = binarizer.fit_transform(dense_array)

# Convert the binarized dense array back to a sparse matrix
binarized_spar = coo_matrix(binarized_dense_array)

# Display the binarized sparse matrix as a dense array for verification
print(binarized_spar.toarray())



[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
