In [1]:
#Imputing missing values through various strategies

In [3]:
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
iris_X = iris.data

In [5]:
masking_array = np.random.binomial(1, .25,iris_X.shape).astype(bool)
iris_X[masking_array] = np.nan

In [7]:
masking_array[:5]

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [ True, False,  True, False],
       [False, False, False,  True]])

In [9]:
iris_X [:5]

array([[5.1, 3.5, 1.4, 0.2],
       [nan, 3. , 1.4, 0.2],
       [4.7, nan, 1.3, 0.2],
       [nan, 3.1, nan, 0.2],
       [5. , 3.6, 1.4, nan]])

In [13]:
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
iris_X = iris.data

# Create the imputer
impute = SimpleImputer(strategy='mean')

# Fit the imputer to the data and transform the data
iris_X_prime = impute.fit_transform(iris_X)

# Display the first 5 rows of the transformed data
print(iris_X_prime[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [15]:
iris_X_prime[0, 0]

5.1

In [17]:
iris_X[0, 0] 

5.1

In [21]:
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
iris_X = iris.data

# Create the imputer with the median strategy
impute = SimpleImputer(strategy='median')

# Fit the imputer to the data and transform the data
iris_X_prime = impute.fit_transform(iris_X)

# Display the first 5 rows of the transformed data
print(iris_X_prime[:5])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [23]:
iris_X[np.isnan(iris_X)] = -1
iris_X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [27]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
iris_X = iris.data

# Introduce some missing values by setting them to -1
iris_X[0, 0] = -1
iris_X[2, 2] = -1

# Create the imputer with the specified missing values and strategy
impute = SimpleImputer(missing_values=-1, strategy='mean')

# Fit the imputer to the data and transform the data
iris_X_prime = impute.fit_transform(iris_X)

# Display the first 5 rows of the transformed data
print(iris_X_prime[:5])


[[5.84832215 3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [4.7        3.2        3.77449664 0.2       ]
 [4.6        3.1        1.5        0.2       ]
 [5.         3.6        1.4        0.2       ]]


In [33]:
import pandas as pd
iris_X_prime = np.where(pd.DataFrame(iris_X).isnull(),-1,iris_X)
iris_X_prime[:5]

array([[-1. ,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2, -1. ,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [31]:
pd.DataFrame(iris_X).fillna(-1)[:5].values

array([[-1. ,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2, -1. ,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])