In [2]:
#Using truncated SVD to reduce dimensionality

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
iris_X = iris.data
y = iris.target

In [6]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(2)
iris_transformed = svd.fit_transform(iris_X)

In [8]:
svd.explained_variance_ratio_

array([0.52875361, 0.44845576])

In [10]:
from scipy.linalg import svd
import numpy as np
D = np.array([[1, 2], [1, 3], [1, 4]])
D

array([[1, 2],
       [1, 3],
       [1, 4]])

In [12]:
U, S, V = svd(D, full_matrices=False)
U.shape, S.shape, V.shape

((3, 2), (2,), (2, 2))

In [14]:
np.dot(U.dot(np.diag(S)), V)

array([[1., 2.],
       [1., 3.],
       [1., 4.]])

In [16]:
new_S = S[0]
new_U = U[:, 0]
new_U.dot(new_S)


tsvd = TruncatedSVD(2)
tsvd.fit(iris_X)
tsvd.transform(iris_X)

array([[ 5.91274714e+00, -2.30203322e+00],
       [ 5.57248242e+00, -1.97182599e+00],
       [ 5.44697714e+00, -2.09520636e+00],
       [ 5.43645948e+00, -1.87038151e+00],
       [ 5.87564494e+00, -2.32829018e+00],
       [ 6.47759822e+00, -2.32464996e+00],
       [ 5.51597520e+00, -2.07090423e+00],
       [ 5.85092859e+00, -2.14807482e+00],
       [ 5.15891972e+00, -1.77506408e+00],
       [ 5.64500117e+00, -1.99000106e+00],
       [ 6.26539771e+00, -2.42576813e+00],
       [ 5.75200785e+00, -2.02037338e+00],
       [ 5.48058085e+00, -1.97777558e+00],
       [ 4.95112411e+00, -2.04828749e+00],
       [ 6.52596417e+00, -2.91606081e+00],
       [ 6.79037199e+00, -2.82500759e+00],
       [ 6.27239468e+00, -2.60811578e+00],
       [ 5.92953789e+00, -2.26766614e+00],
       [ 6.64813130e+00, -2.38959506e+00],
       [ 6.09486463e+00, -2.36082303e+00],
       [ 6.25397363e+00, -2.12001187e+00],
       [ 6.07364677e+00, -2.27178150e+00],
       [ 5.36999813e+00, -2.49808604e+00],
       [ 6.